theme: jekyll-theme-slate
title: [Katalog vzorů řešení pro problémy při zajištění integrity v relačním systému řízení báze dat Oracle]
description: [Na této stránce je uveden katalog vzorů řešení pro problémy při zajištění integrity v relačním systémů řízení báze dat Oracle, který vznikl jako výsledek mé bakalářské práce. /n Autor: Tomáš Waller]
